name: sam
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pip=23.0.1
  - python=3.9.16
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - pip:
    - opencv-python==4.7.0.72
    - numpy==1.24.1
    - matplotlib==3.7.1
    - segment-anything==1.0
    - notebook==6.5.4

